#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/common.sh"

wasm_cmake -S "${LLVM_SOURCE_DIR}/llvm" -B "${WASM_LLVM_DIR}" -G Ninja \
  -DCMAKE_MAKE_PROGRAM="${NINJA}" -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_HOST_TRIPLE=wasm32-unknown-emscripten \
  -DLLVM_TARGETS_TO_BUILD=WebAssembly -DLLVM_ENABLE_PROJECTS='clang;lld' \
  -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_ENABLE_THREADS=ON \
  -DLLVM_ENABLE_ZLIB=OFF -DLLVM_ENABLE_ZSTD=OFF \
  -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_LIBEDIT=OFF \
  -DLLVM_ENABLE_PLUGINS=OFF -DLLVM_ENABLE_PIC=OFF \
  -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF \
  -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_DOCS=OFF \
  -DLLVM_BUILD_TOOLS=OFF -DLLVM_BUILD_UTILS=OFF \
  -DCLANG_BUILD_TOOLS=OFF -DCLANG_ENABLE_STATIC_ANALYZER=OFF \
  -DCLANG_ENABLE_OBJC_REWRITER=OFF -DCLANG_ENABLE_BOOTSTRAP=OFF \
  -DCLANG_PLUGIN_SUPPORT=OFF -DCLANG_ENABLE_LIBXML2=OFF \
  -DCLANG_TOOL_INDEXSTORE_BUILD=OFF \
  -DLLVM_NATIVE_TOOL_DIR="${NATIVE_LLVM_DIR}/bin" \
  -DLLVM_TABLEGEN="${NATIVE_LLVM_DIR}/bin/llvm-tblgen" \
  -DCLANG_TABLEGEN="${NATIVE_LLVM_DIR}/bin/clang-tblgen" \
  -DCMAKE_C_FLAGS="${WASM_FLAGS}" -DCMAKE_CXX_FLAGS="${WASM_CXX_FLAGS}" \
  -DCMAKE_EXE_LINKER_FLAGS='-pthread -sALLOW_MEMORY_GROWTH=1' \
  -DLLVM_PARALLEL_LINK_JOBS=1
