#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/common.sh"

mode="${1:-guest}"
case "${mode}" in
  guest) build=stdlib-wasm; threading=none; c_flags=-fPIC ;;
  host) build=stdlib-host-wasm; threading=pthreads; c_flags='-fPIC -pthread' ;;
  *) printf 'Expected guest or host, got %s\n' "${mode}" >&2; exit 1 ;;
esac
swift_flags="-Xcc;-fPIC;-Xcc;-mno-reference-types;-Xcc;-isystem;-Xcc;${EMSCRIPTEN_ROOT}/cache/sysroot/include/compat"
if [[ "${mode}" == host ]]; then
  swift_flags="${swift_flags};-Xcc;-pthread"
fi
# The compiler runtime uses pthreads. WAMR executes single-threaded programs.
wasm_cmake -S "${SWIFT_SOURCE_DIR}" -B "${WORK_DIR}/${build}" -G Ninja \
  -DCMAKE_MAKE_PROGRAM="${NINJA}" -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SYSTEM_PROCESSOR=wasm32 -DUNIX=TRUE \
  -DCMAKE_C_FLAGS="${c_flags}" -DCMAKE_CXX_FLAGS="${c_flags}" \
  -DLLVM_DIR="${WASM_LLVM_DIR}/lib/cmake/llvm" \
  -DSWIFT_NATIVE_SWIFT_TOOLS_PATH="${NATIVE_SWIFT_DIR}/bin" \
  -DSWIFT_NATIVE_CLANG_TOOLS_PATH="${EMSDK_ROOT}/upstream/bin" \
  -DSWIFT_NATIVE_LLVM_TOOLS_PATH="${NATIVE_LLVM_DIR}/bin" \
  -DSWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER=ON \
  -DSWIFT_INCLUDE_TOOLS=OFF -DSWIFT_INCLUDE_TESTS=OFF -DSWIFT_INCLUDE_DOCS=OFF \
  -DSWIFT_ENABLE_SWIFT_IN_SWIFT=ON -DBOOTSTRAPPING_MODE=CROSSCOMPILE \
  -DSWIFT_BUILD_SOURCEKIT=OFF -DSWIFT_BUILD_SWIFT_SYNTAX=OFF \
  -DSWIFT_BUILD_REMOTE_MIRROR=OFF -DSWIFT_ENABLE_DISPATCH=OFF \
  -DSWIFT_PRIMARY_VARIANT_SDK=EMSCRIPTEN -DSWIFT_PRIMARY_VARIANT_ARCH=wasm32 \
  -DSWIFT_SDKS=EMSCRIPTEN \
  -DSWIFT_EMSCRIPTEN_SYSROOT_PATH="${EMSCRIPTEN_ROOT}/cache/sysroot" \
  -DSWIFT_STDLIB_BUILD_TYPE=Release -DSWIFT_BUILD_STATIC_STDLIB=ON \
  -DSWIFT_BUILD_DYNAMIC_STDLIB=OFF -DSWIFT_BUILD_STATIC_SDK_OVERLAY=ON \
  -DSWIFT_STDLIB_INSTALL_ONLY_CLANG_RESOURCE_HEADERS=ON \
  -DSWIFT_STDLIB_STABLE_ABI=ON -DSWIFT_STDLIB_TRACING=OFF \
  -DSWIFT_STDLIB_HAS_ASLR=OFF -DSWIFT_STDLIB_HAS_DLADDR=OFF \
  -DSWIFT_STDLIB_SUPPORT_BACK_DEPLOYMENT=OFF \
  -DSWIFT_STDLIB_INSTALL_PARENT_MODULE_FOR_SHIMS=OFF \
  -DSWIFT_RUNTIME_CRASH_REPORTER_CLIENT=OFF \
  -DSWIFT_STDLIB_SINGLE_THREADED_CONCURRENCY=ON \
  -DSWIFT_STDLIB_SUPPORTS_BACKTRACE_REPORTING=OFF \
  -DSWIFT_STDLIB_COMPACT_ABSOLUTE_FUNCTION_POINTER=ON \
  -DSWIFT_THREADING_PACKAGE="${threading}" \
  -DSWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING=ON \
  -DSWIFT_PATH_TO_STRING_PROCESSING_SOURCE="${SWIFT_DEV_DIR}/swift-experimental-string-processing" \
  -DSWIFT_SHOULD_BUILD_EMBEDDED_STDLIB=OFF \
  -DSWIFT_STDLIB_EXTRA_C_COMPILE_FLAGS="-fPIC;-isystem;${EMSCRIPTEN_ROOT}/cache/sysroot/include/compat" \
  -DSWIFT_STDLIB_EXTRA_SWIFT_COMPILE_FLAGS="${swift_flags}" \
  -DSWIFT_PARALLEL_LINK_JOBS=1
