name: wasmbolt-wasm-host

channels:
  - https://repo.prefix.dev/emscripten-forge-bot/emscripten-forge-6x
  - conda-forge

dependencies:
  - llvm-static =23.1.2
  - clangdev-static =23.1.2
  - lld-static =23.1.2
  - llvm-tools =23.1.2
  - mlir =23.1.2
  - graphviz =15.1.0

  # Optional libraries: enable compatible packages for your deployment.
  # - boost-cpp
  # - symengine
