#ifndef WASMBOLT_WAMR_EMSCRIPTEN_WASI_COMPAT_H
#define WASMBOLT_WAMR_EMSCRIPTEN_WASI_COMPAT_H

#include <wasi/api.h>

#define __WASI_ESUCCESS        __WASI_ERRNO_SUCCESS
#define __WASI_E2BIG           __WASI_ERRNO_2BIG
#define __WASI_EACCES          __WASI_ERRNO_ACCES
#define __WASI_EADDRINUSE      __WASI_ERRNO_ADDRINUSE
#define __WASI_EADDRNOTAVAIL   __WASI_ERRNO_ADDRNOTAVAIL
#define __WASI_EAFNOSUPPORT    __WASI_ERRNO_AFNOSUPPORT
#define __WASI_EAGAIN          __WASI_ERRNO_AGAIN
#define __WASI_EALREADY        __WASI_ERRNO_ALREADY
#define __WASI_EBADF           __WASI_ERRNO_BADF
#define __WASI_EBADMSG         __WASI_ERRNO_BADMSG
#define __WASI_EBUSY           __WASI_ERRNO_BUSY
#define __WASI_ECANCELED       __WASI_ERRNO_CANCELED
#define __WASI_ECHILD          __WASI_ERRNO_CHILD
#define __WASI_ECONNABORTED    __WASI_ERRNO_CONNABORTED
#define __WASI_ECONNREFUSED    __WASI_ERRNO_CONNREFUSED
#define __WASI_ECONNRESET      __WASI_ERRNO_CONNRESET
#define __WASI_EDEADLK         __WASI_ERRNO_DEADLK
#define __WASI_EDESTADDRREQ    __WASI_ERRNO_DESTADDRREQ
#define __WASI_EDOM            __WASI_ERRNO_DOM
#define __WASI_EDQUOT          __WASI_ERRNO_DQUOT
#define __WASI_EEXIST          __WASI_ERRNO_EXIST
#define __WASI_EFAULT          __WASI_ERRNO_FAULT
#define __WASI_EFBIG           __WASI_ERRNO_FBIG
#define __WASI_EHOSTUNREACH    __WASI_ERRNO_HOSTUNREACH
#define __WASI_EIDRM           __WASI_ERRNO_IDRM
#define __WASI_EILSEQ          __WASI_ERRNO_ILSEQ
#define __WASI_EINPROGRESS     __WASI_ERRNO_INPROGRESS
#define __WASI_EINTR           __WASI_ERRNO_INTR
#define __WASI_EINVAL          __WASI_ERRNO_INVAL
#define __WASI_EIO             __WASI_ERRNO_IO
#define __WASI_EISCONN         __WASI_ERRNO_ISCONN
#define __WASI_EISDIR          __WASI_ERRNO_ISDIR
#define __WASI_ELOOP           __WASI_ERRNO_LOOP
#define __WASI_EMFILE          __WASI_ERRNO_MFILE
#define __WASI_EMLINK          __WASI_ERRNO_MLINK
#define __WASI_EMSGSIZE        __WASI_ERRNO_MSGSIZE
#define __WASI_EMULTIHOP       __WASI_ERRNO_MULTIHOP
#define __WASI_ENAMETOOLONG    __WASI_ERRNO_NAMETOOLONG
#define __WASI_ENETDOWN        __WASI_ERRNO_NETDOWN
#define __WASI_ENETRESET       __WASI_ERRNO_NETRESET
#define __WASI_ENETUNREACH     __WASI_ERRNO_NETUNREACH
#define __WASI_ENFILE          __WASI_ERRNO_NFILE
#define __WASI_ENOBUFS         __WASI_ERRNO_NOBUFS
#define __WASI_ENODEV          __WASI_ERRNO_NODEV
#define __WASI_ENOENT          __WASI_ERRNO_NOENT
#define __WASI_ENOEXEC         __WASI_ERRNO_NOEXEC
#define __WASI_ENOLCK          __WASI_ERRNO_NOLCK
#define __WASI_ENOLINK         __WASI_ERRNO_NOLINK
#define __WASI_ENOMEM          __WASI_ERRNO_NOMEM
#define __WASI_ENOMSG          __WASI_ERRNO_NOMSG
#define __WASI_ENOPROTOOPT     __WASI_ERRNO_NOPROTOOPT
#define __WASI_ENOSPC          __WASI_ERRNO_NOSPC
#define __WASI_ENOSYS          __WASI_ERRNO_NOSYS
#define __WASI_ENOTCONN        __WASI_ERRNO_NOTCONN
#define __WASI_ENOTDIR         __WASI_ERRNO_NOTDIR
#define __WASI_ENOTEMPTY       __WASI_ERRNO_NOTEMPTY
#define __WASI_ENOTRECOVERABLE __WASI_ERRNO_NOTRECOVERABLE
#define __WASI_ENOTSOCK        __WASI_ERRNO_NOTSOCK
#define __WASI_ENOTSUP         __WASI_ERRNO_NOTSUP
#define __WASI_ENOTTY          __WASI_ERRNO_NOTTY
#define __WASI_ENXIO           __WASI_ERRNO_NXIO
#define __WASI_EOVERFLOW       __WASI_ERRNO_OVERFLOW
#define __WASI_EOWNERDEAD      __WASI_ERRNO_OWNERDEAD
#define __WASI_EPERM           __WASI_ERRNO_PERM
#define __WASI_EPIPE           __WASI_ERRNO_PIPE
#define __WASI_EPROTO          __WASI_ERRNO_PROTO
#define __WASI_EPROTONOSUPPORT __WASI_ERRNO_PROTONOSUPPORT
#define __WASI_EPROTOTYPE      __WASI_ERRNO_PROTOTYPE
#define __WASI_ERANGE          __WASI_ERRNO_RANGE
#define __WASI_EROFS           __WASI_ERRNO_ROFS
#define __WASI_ESPIPE          __WASI_ERRNO_SPIPE
#define __WASI_ESRCH           __WASI_ERRNO_SRCH
#define __WASI_ESTALE          __WASI_ERRNO_STALE
#define __WASI_ETIMEDOUT       __WASI_ERRNO_TIMEDOUT
#define __WASI_ETXTBSY         __WASI_ERRNO_TXTBSY
#define __WASI_EXDEV           __WASI_ERRNO_XDEV
#define __WASI_ENOTCAPABLE     __WASI_ERRNO_NOTCAPABLE

#define __WASI_CLOCK_REALTIME           __WASI_CLOCKID_REALTIME
#define __WASI_CLOCK_MONOTONIC          __WASI_CLOCKID_MONOTONIC
#define __WASI_CLOCK_PROCESS_CPUTIME_ID __WASI_CLOCKID_PROCESS_CPUTIME_ID
#define __WASI_CLOCK_THREAD_CPUTIME_ID  __WASI_CLOCKID_THREAD_CPUTIME_ID

#endif

