#!/usr/bin/env python3
"""Stage only browser assets. Preserve all source and build directories."""
import argparse
import gzip
import json
import shutil
from pathlib import Path

root = Path(__file__).resolve().parents[3]
recipe = root / 'debugger/lldb'
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--compiler-build', type=Path, default=root / 'build/wasm32')
p.add_argument('--tools-prefix', type=Path, required=True)
p.add_argument('--debugger-output', type=Path, default=recipe / '.work/output')
p.add_argument('--guest-sysroot', type=Path, required=True)
p.add_argument('--library-include', type=Path, help='Optional nlohmann_json or xtensor/xtl header prefix')
p.add_argument('--compress', action='store_true', help='Precompress large assets for the demo server')
p.add_argument('--site', type=Path, default=root / 'site')
a = p.parse_args()
site = a.site.resolve()
if site == root or site in root.parents:
    p.error('Choose a separate generated site directory')

def copy(source, target):
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)

copy(root / 'ui/index.html', site / 'index.html')
for directory, patterns in [('ui', ['*.js', '*.css']), ('runtime', ['*.js']),
                            ('tools', ['*.js']), ('compilers/swift', ['*.js'])]:
    for pattern in patterns:
        for source in (root / directory).glob(pattern):
            copy(source, site / directory / source.name)
for suffix in ['js', 'wasm', 'data']:
    copy(a.compiler_build / ('Compiler.' + suffix), site / 'runtime' / ('Compiler.' + suffix))
for tool in ['opt', 'llc', 'llvm-ar', 'llvm-cxxfilt', 'llvm-nm', 'llvm-objcopy', 'llvm-objdump',
             'llvm-readobj', 'llvm-size', 'mlir-opt', 'mlir-translate', 'dot']:
    for suffix in ['js', 'wasm']:
        copy(a.tools_prefix / 'bin' / (tool + '.' + suffix), site / 'tools' / (tool + '.' + suffix))
for source in [root / 'tutorials.md', *root.glob('tutorial_*.md')]:
    copy(source, site / source.name)
destination = site / 'debugger/lldb'
for source in recipe.glob('*.js'):
    copy(source, destination / source.name)
for name in ['lldb-dap.js', 'lldb-dap.wasm', 'lldb-dap.worker.js']:
    copy(a.debugger_output / name, destination / name)
for source in (recipe / 'tests').glob('*'):
    copy(source, destination / 'tests' / source.name)
# WASI guest link inputs, generated by 60-build-test-guests.sh with the same SDK.
names = ['crt1.o'] + ['lib' + name + '.a' for name in ['standalonewasm-nocatch', 'stubs-debug',
    'c-debug', 'dlmalloc-debug', 'clang_rt.builtins', 'c++-debug-noexcept', 'c++abi-debug-noexcept']]
files = []
for name in names:
    relative = Path('guest/lib/wasm32-emscripten') / name
    copy(a.guest_sysroot / 'lib/wasm32-emscripten' / name, destination / relative)
    files.append({'path': '/lib/wasm32-emscripten/' + name, 'url': relative.as_posix()})
if a.library_include:
    for directory in ['nlohmann', 'xtensor', 'xtl']:
        base = a.library_include / directory
        if not base.is_dir():
            continue
        for source in base.rglob('*'):
            if source.is_file():
                path = Path(directory) / source.relative_to(base)
                relative = Path('guest/include') / path
                copy(source, destination / relative)
                files.append({'path': '/include/' + path.as_posix(), 'url': relative.as_posix()})
examples = {name: (recipe / 'tests' / name).read_text()
            for name in ['simple.cpp', 'simple.c', 'debug.ll', 'json.cpp']}
(destination / 'workspace-examples.json').write_text(json.dumps(examples) + '\n')
(destination / 'guest-files.json').write_text(json.dumps(files, indent=2) + '\n')
(site / '_headers').write_text('/*\n  Cross-Origin-Opener-Policy: same-origin\n'
    '  Cross-Origin-Embedder-Policy: require-corp\n  Cross-Origin-Resource-Policy: same-origin\n')
if a.compress:
    for source in site.rglob('*'):
        if source.suffix in ['.wasm', '.data', '.a'] and source.is_file():
            with source.open('rb') as input_file, gzip.open(str(source) + '.gz', 'wb', compresslevel=6) as output_file:
                shutil.copyfileobj(input_file, output_file)
print('Staged browser site:', site)
