name: wasmbolt-swift-build
channels:
  - https://repo.prefix.dev/emscripten-forge-bot/emscripten-forge-6x
  - conda-forge
dependencies:
  - emscripten-core=6.0.8
  - cmake>=4.3.3
  - ninja
  - make
  - python>=3.10
  - nodejs>=22
